// One-time (idempotent) repair for Roll Numbers corrupted by a bug in
// resolveRollNumberAvoidingCollisions() (see utils/studentIdentifiers.js) — when 3+ students in
// the same Academic Group had colliding auto-generated Roll Numbers, the old collision-resolution
// loop kept sliding its 3-character window left through the whole Registration Number (PRN),
// eventually walking into the alphabetic institute/batch/department code that precedes a PRN's
// numeric suffix and handing that fragment out as a "Roll Number" (e.g. a group of PRNs like
// "...UMXF2001".."...UMXF2005" produced Roll Numbers "MXF"/"UMX"/"XF2"/"F20" once several students
// collided). Those letter-containing values also always sort last (see compareRollNumbers), which
// is what actually surfaced the bug as a "sort" complaint.
//
// This script finds every such garbled row (a 3-character Roll Number containing a letter, that
// is also a literal substring of that same student's own Registration Number — the fingerprint
// that proves it was auto-generated by the buggy resolver rather than a real value someone typed
// in) and regenerates it with the fixed resolver. Only ever touches rows matching that exact
// fingerprint; every already-clean numeric Roll Number (garbled or not) is left untouched.
const prisma = require("../src/prisma");
const { resolveRollNumberAvoidingCollisions } = require("../src/utils/studentIdentifiers");

async function backfillGarbledRollNumbers() {
  const students = await prisma.user.findMany({
    where: { role: "STUDENT", rollNumber: { not: null }, registrationNumber: { not: null }, academicGroupId: { not: null } },
    select: { id: true, rollNumber: true, registrationNumber: true, academicGroupId: true, createdAt: true },
    orderBy: { createdAt: "asc" },
  });

  const isGarbled = (s) =>
    s.rollNumber.length === 3 &&
    /[A-Za-z]/.test(s.rollNumber) &&
    s.registrationNumber.toUpperCase().includes(s.rollNumber.toUpperCase());

  const byGroup = new Map();
  for (const s of students) {
    if (!byGroup.has(s.academicGroupId)) byGroup.set(s.academicGroupId, []);
    byGroup.get(s.academicGroupId).push(s);
  }

  let fixed = 0;
  for (const [, groupStudents] of byGroup) {
    const garbled = groupStudents.filter(isGarbled);
    if (garbled.length === 0) continue;

    // Seed `taken` with every already-clean Roll Number in the group so a regenerated value can
    // never collide with a student who isn't part of this repair.
    const taken = new Set(groupStudents.filter((s) => !isGarbled(s)).map((s) => s.rollNumber));

    for (const s of garbled) {
      const next = resolveRollNumberAvoidingCollisions(s.registrationNumber, taken);
      if (!next || next === s.rollNumber) continue;
      taken.add(next);
      await prisma.user.update({ where: { id: s.id }, data: { rollNumber: next } });
      fixed++;
    }
  }

  return { scanned: students.length, fixed };
}

async function main() {
  const { scanned, fixed } = await backfillGarbledRollNumbers();
  console.log(`[backfillGarbledRollNumbers] Scanned ${scanned} student(s), repaired ${fixed} garbled Roll Number(s).`);
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("[backfillGarbledRollNumbers] failed:", err);
  process.exit(1);
});
