const prisma = require("../prisma");
const { getClientIp } = require("./clientIp");

// Coarse User-Agent parsing — this platform only needs enough precision for an admin skimming a
// login-history list to recognize "that's not my usual browser," not full device fingerprinting.
function parseDevice(userAgent) {
  const ua = String(userAgent || "");

  let browser = "Unknown browser";
  if (/edg\//i.test(ua)) browser = "Edge";
  else if (/chrome\//i.test(ua) && !/edg\//i.test(ua)) browser = "Chrome";
  else if (/firefox\//i.test(ua)) browser = "Firefox";
  else if (/safari\//i.test(ua) && !/chrome\//i.test(ua)) browser = "Safari";

  let os = "Unknown OS";
  if (/windows/i.test(ua)) os = "Windows";
  else if (/mac os x/i.test(ua)) os = "macOS";
  else if (/android/i.test(ua)) os = "Android";
  else if (/iphone|ipad|ios/i.test(ua)) os = "iOS";
  else if (/linux/i.test(ua)) os = "Linux";

  const device = /ipad|tablet/i.test(ua) ? "Tablet" : /mobile/i.test(ua) ? "Mobile" : "Desktop";

  return { browser, os, device, summary: `${browser} on ${os}` };
}

// Catalogue of action strings this platform writes, kept here as documentation only — `action`
// stays a free-text column (see AuditLog.action comment in schema.prisma) so a new call site
// doesn't need a schema migration, but every writer should pick a name from (or matching the
// style of) this list rather than inventing an inconsistent one.
const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_BLOCKED: "PASSWORD_RESET_BLOCKED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  STUDENT_PROFILE_UPDATED: "STUDENT_PROFILE_UPDATED",
  TEST_CREATED: "TEST_CREATED",
  TEST_UPDATED: "TEST_UPDATED",
  TEST_UNPUBLISHED: "TEST_UNPUBLISHED",
  TEST_DUPLICATED: "TEST_DUPLICATED",
  TEST_DELETED: "TEST_DELETED",
  TEST_ASSIGNED: "TEST_ASSIGNED",
  RESULT_MODIFIED: "RESULT_MODIFIED",
  REATTEMPT_GRANTED: "REATTEMPT_GRANTED",
  CERTIFICATE_ISSUED: "CERTIFICATE_ISSUED",
  CERTIFICATE_REVOKED: "CERTIFICATE_REVOKED",
  QUESTION_BANK_CHANGED: "QUESTION_BANK_CHANGED",
  USER_MANAGEMENT_CHANGED: "USER_MANAGEMENT_CHANGED",
  INSTITUTE_CONFIG_CHANGED: "INSTITUTE_CONFIG_CHANGED",
  SESSION_REVOKED: "SESSION_REVOKED",
  DATABASE_BACKUP_DOWNLOADED: "DATABASE_BACKUP_DOWNLOADED",
  DATA_EXPORTED: "DATA_EXPORTED",
  AI_AUTO_REFRESH_RUN: "AI_AUTO_REFRESH_RUN",
  CHALLENGE_AUTO_SCHEDULE_RUN: "CHALLENGE_AUTO_SCHEDULE_RUN",
  COMPANY_INTERVIEW_PROFILE_SAVED: "COMPANY_INTERVIEW_PROFILE_SAVED",
  COMPANY_INTERVIEW_PROFILE_DELETED: "COMPANY_INTERVIEW_PROFILE_DELETED",
  STAFF_CLASS_ASSIGNMENT_CHANGED: "STAFF_CLASS_ASSIGNMENT_CHANGED",
  STAFF_SUBJECT_ASSIGNMENT_CHANGED: "STAFF_SUBJECT_ASSIGNMENT_CHANGED",
  ATTENDANCE_MARKED: "ATTENDANCE_MARKED",
  COURSE_MANAGEMENT_CHANGED: "COURSE_MANAGEMENT_CHANGED",
  CONTENT_VERSION_CREATED: "CONTENT_VERSION_CREATED",
  CONTENT_VERSION_PUBLISHED: "CONTENT_VERSION_PUBLISHED",
  CONTENT_VERSION_RESTORED: "CONTENT_VERSION_RESTORED",
  CHALLENGE_SCHEDULED: "CHALLENGE_SCHEDULED",
  CHALLENGE_TOGGLED: "CHALLENGE_TOGGLED",
  CHALLENGE_ARCHIVED: "CHALLENGE_ARCHIVED",
  CHALLENGE_REMOVED: "CHALLENGE_REMOVED",
  CHALLENGE_DUPLICATED: "CHALLENGE_DUPLICATED",
  COMPANY_MASTER_CHANGED: "COMPANY_MASTER_CHANGED",
  PLACEMENT_OFFER_VERIFIED: "PLACEMENT_OFFER_VERIFIED",
  PLACEMENT_ELIGIBILITY_CHANGED: "PLACEMENT_ELIGIBILITY_CHANGED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_UPDATED: "DOCUMENT_UPDATED",
  DOCUMENT_VERIFIED: "DOCUMENT_VERIFIED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
  TALENT_POOL_CREATED: "TALENT_POOL_CREATED",
  TALENT_POOL_UPDATED: "TALENT_POOL_UPDATED",
  TALENT_POOL_DELETED: "TALENT_POOL_DELETED",
  TALENT_POOL_MEMBERS_CHANGED: "TALENT_POOL_MEMBERS_CHANGED",
  TALENT_POOL_AUTO_RULE_RUN: "TALENT_POOL_AUTO_RULE_RUN",
  TALENT_POOL_ASSESSMENT_ASSIGNED: "TALENT_POOL_ASSESSMENT_ASSIGNED",
  TALENT_POOL_ATTENDANCE_OWNER_ASSIGNED: "TALENT_POOL_ATTENDANCE_OWNER_ASSIGNED",
  TALENT_POOL_ATTENDANCE_OWNER_REMOVED: "TALENT_POOL_ATTENDANCE_OWNER_REMOVED",
  TALENT_POOL_BULK_IMPORT: "TALENT_POOL_BULK_IMPORT",
  TALENT_POOL_MEMBERS_TRANSFERRED: "TALENT_POOL_MEMBERS_TRANSFERRED",
  RESULT_EXAMINATION_CREATED: "RESULT_EXAMINATION_CREATED",
  RESULT_EXAMINATION_EDITED: "RESULT_EXAMINATION_EDITED",
  RESULT_EXAMINATION_PUBLISHED: "RESULT_EXAMINATION_PUBLISHED",
  RESULT_EXAMINATION_UNPUBLISHED: "RESULT_EXAMINATION_UNPUBLISHED",
  RESULT_EXAMINATION_DELETED: "RESULT_EXAMINATION_DELETED",
  RESULT_ENTRIES_BULK_IMPORTED: "RESULT_ENTRIES_BULK_IMPORTED",
  RESULT_ENTRY_CREATED: "RESULT_ENTRY_CREATED",
  RESULT_ENTRY_EDITED: "RESULT_ENTRY_EDITED",
  RESULT_ENTRY_DELETED: "RESULT_ENTRY_DELETED",
  RESULT_ENTRY_CORRECTED: "RESULT_ENTRY_CORRECTED",
  RESULT_EXAMINATION_SUBMITTED_FOR_REVIEW: "RESULT_EXAMINATION_SUBMITTED_FOR_REVIEW",
  RESULT_EXAMINATION_MARKED_READY: "RESULT_EXAMINATION_MARKED_READY",
  RESULT_EXAMINATION_SENT_BACK_TO_DRAFT: "RESULT_EXAMINATION_SENT_BACK_TO_DRAFT",
  RESULT_EXAMINATION_ARCHIVED: "RESULT_EXAMINATION_ARCHIVED",
  RESULT_GRADE_SCALE_UPDATED: "RESULT_GRADE_SCALE_UPDATED",
  RESULT_EXPORTED: "RESULT_EXPORTED",
  ACCOUNT_ACTIVATED: "ACCOUNT_ACTIVATED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED: "ACCOUNT_UNLOCKED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_DELETED: "USER_DELETED",
  QUESTION_CREATED: "QUESTION_CREATED",
  QUESTION_UPDATED: "QUESTION_UPDATED",
  QUESTION_DELETED: "QUESTION_DELETED",
  QUESTION_IMPORTED: "QUESTION_IMPORTED",
  QUESTION_EXPORTED: "QUESTION_EXPORTED",
  READINESS_SUBJECT_SAVED: "READINESS_SUBJECT_SAVED",
  READINESS_SUBJECT_DELETED: "READINESS_SUBJECT_DELETED",
  READINESS_TEST_ASSIGNED: "READINESS_TEST_ASSIGNED",
  QUESTION_BANK_SHARED: "QUESTION_BANK_SHARED",
  TEST_PUBLISHED: "TEST_PUBLISHED",
  INTERVIEW_SESSION_STARTED: "INTERVIEW_SESSION_STARTED",
  INTERVIEW_SESSION_RESUMED: "INTERVIEW_SESSION_RESUMED",
  INTERVIEW_SESSION_COMPLETED: "INTERVIEW_SESSION_COMPLETED",
  INTERVIEW_SESSION_TERMINATED: "INTERVIEW_SESSION_TERMINATED",
  INTERVIEW_VIOLATION_RECORDED: "INTERVIEW_VIOLATION_RECORDED",
  EMAIL_RETRIED: "EMAIL_RETRIED",
  EMAIL_TEST_SENT: "EMAIL_TEST_SENT",
  FEATURE_TOGGLED: "FEATURE_TOGGLED",
  FEATURE_BULK_TOGGLED: "FEATURE_BULK_TOGGLED",
  FEATURE_CONFIG_COPIED: "FEATURE_CONFIG_COPIED",
};

// Never throws — audit logging is a best-effort side channel (same posture as this codebase's
// email-send tracking) and must not be able to fail the request it's describing.
async function logAudit({ req, action, actorId, actorName, actorRole, studentId, instituteId, details }) {
  try {
    await prisma.auditLog.create({
      data: {
        action,
        adminId: actorId || "system",
        adminName: actorName || "System",
        adminRole: actorRole || null,
        ipAddress: req ? getClientIp(req) : null,
        deviceInfo: req ? parseDevice(req.headers["user-agent"]).summary : null,
        studentId: studentId || null,
        instituteId: instituteId || null,
        details: details || {},
      },
    });
  } catch (err) {
    console.error("Failed to write audit log:", err);
  }
}

module.exports = { logAudit, parseDevice, AUDIT_ACTIONS };
